
services:
  db:
    image: postgres:latest
    container_name: event-planner-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
  
    networks:
      - mynetwork

volumes:
  pg_data:

networks:
  mynetwork:
    driver: bridge